sudo: false
language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- pypy
cache:
  directories:
  - $HOME/.pip-cache/
install:
- pip install -U pip --cache-dir $HOME/.pip-cache
- pip install -e .[test] --cache-dir $HOME/.pip-cache
script:
- py.test --cov mbx --cov-report term-missing
after_success:
- coveralls
