sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
cache:
  directories:
  - $HOME/.pip-cache/
env:
  global:
  - PIP_CACHE_DIR=$HOME/.pip-cache
  - PIP_CONSTRAINT=constraints.txt
install:
- pip install -U pip
- pip install --no-cache -r requirements-dev.txt
- pip install --no-cache -e .[test]
- pip list
script:
- py.test -vv --cov mapboxcli --cov-report term-missing
after_success:
- coveralls
deploy:
  on:
    tags: true
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: mapboxci
